version: '3.8'

services:
  nestjs_api:
    container_name: nestjs_api
    image: nestjs_api:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: yarn start:dev
    ports:
      - 3000:3002
      - 9229:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  database:
    container_name: database
    image: postgres:11-alpine
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 15432:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PG_DATA=/var/lib/postgresql/data
